

services:
  app_one:
    build: 
      context: ./app-one
      dockerfile: Dockerfile
    container_name: one_app
    restart: always
    expose:
      - "8000"

  
  app_four:
    build: 
      context: ./Academic_Issue_Tracking_system/backend
      dockerfile: Dockerfile
    container_name: four_app
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./Academic_Issue_Tracking_system/backend:/app
      - ./Academic_Issue_Tracking_system/backend/media:/app/media
      - ./Academic_Issue_Tracking_system/backend/staticfiles:/app/staticfiles
    restart: always
    expose:
      - "8000"
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*

