events {

    worker_connections  1024;
}


http {
    server {
        listen 80;
        server_name _;

        # Health check endpoint
        location / {
    return 200 "Server is running\n";
        }

        # App one endpoint
        location /app_one/ {
            proxy_pass http://one_app:8000/;

            add_header X-Upstream $upstream_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        # App one endpoint
        location /app_two/ {
            proxy_pass http://two_app:8000/;

            add_header X-Upstream $upstream_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        # App one endpoint
        location /app_three/ {
            proxy_pass http://three_app:8000/;

            add_header X-Upstream $upstream_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # App four endpoint
        location /app_four/ {
            proxy_pass http://four_app:8000/;

            add_header X-Upstream $upstream_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
}
}

